[faults]
fifo_path="/tmp/faults.fifo"
[cache]
apply_eviction=false
[cache.simple]
custom_size="1gb"
blocks_per_page=1
# [cache.manual]
# io_block_size=4096
# page_size=4096
# no_pages=10
[filesystem]
log_all_operations=true
logfile="/home/gsd/lfs.log"


#[[injection]]
#type="split_write"
#file="/home/gsd/test_postgres/postgres-r/postgresql/15/main/base/5/16400"
#ocurrence=10000000
#parts=2
#persist=2

#[[injection]]
#type="reorder"
#op="write"
#file="/home/gsd/data/zk37-root/version-2/log.100000001"
#persist=[2,4]

#[[injection]]
#type="split_write"
#file="/home/gsd/data/zk37-root/version-2/log.100000001"
#ocurrence=3
#parts=2
#persist=2

[[injection]]
type="split_write"
file="/home/gsd/data/zk37-root/version-2/log.100000001"
ocurrence=3
parts=2
persist=2

#[[injection]]
#type="reorder"
#op="write"
#file="/home/gsd/data/zookeeper-root/version-2/log.100000001"
#persist=[2,4]

#[[injection]]
#type="reorder"
#file="/home/gsd/data/zookeeper-root/version-2/log.100000001"
#ocurrence=3
#parts=2
#persist=2

#[[injection]]
#type="reorder"
#op="write"
#persist=[2]
#file="/home/gsd/etcd-v3.4.25-linux-amd64/data-r/data.etcd/member/wal/0000000000000000-0000000000000000.wal"

#[[injection]]
#type="split_write"
#file="/home/gsd/etcd-v3.4.25-linux-amd64/data-r/data.etcd/member/wal/0.tmp"
#persist=2
#parts=2
#ocurrence=1

#[[injection]]
#type="reorder"
#op="write"
#file="/home/gsd/etcd-v3.4.25-linux-amd64/data-r/data.etcd/member/snap/db"
#persist=[2]

#[[injection]]
#type="reorder"
#op="write"
#file="/home/gsd/etcd-v2.3.0-linux-amd64/data-r/data.etcd/member/wal/0000000000000000-0000000000000000.wal"
#persist=[2]

#[[injection]]
#type="split_write"
#file="/home/gsd/leveldb-testes/data-r/000003.log"
#ocurrence=4
#parts_bytes=[4096,1903]
#persist=[1]

#[[injection]]
#type="reorder"
#op="write"
#file="/home/gsd/leveldb-testes/data-r/000003.log"
#persist=[1]

#[[injection]]
#type="reorder"
#op="write"
#file="/home/gsd/leveldb-testes/data-r/000003.log"
#persist=[1,3,5]

#[[injection]]
#type="split_write"
#file="/home/gsd/leveldb-testes/data-r/000003.log"
#ocurrence=4
#parts=4
#persist=[1,2,4]

[[injection]]
type="split_write"
file="/home/gsd/pebble-testes/data-r/000002.log"
ocurrence=4
parts_bytes=[4096,1911]
persist=[2]