[faults]
fifo_path="/tmp/faults.fifo"
[cache]
apply_eviction=false
[cache.simple]
custom_size="1gb"
blocks_per_page=1
# [cache.manual]
# io_block_size=4096
# page_size=4096
# no_pages=10
[filesystem]
log_all_operations=true
logfile="/home/gsd/lfs.log"

[[injection]]
type="split_write"
<<<<<<< HEAD
file="/home/gsd/etcd-v3.4.25-linux-amd64/data-r/data.etcd/member/snap/db"
persist=[2]
parts=2
ocurrence=1

[[injection]]
type="split_write"
ocurrence=45
file="/home/gsd/test_cockroachDB/data-node2/node2-r/000282.log"
parts=3
persist=[2]

#[[injection]]
#type="reorder"
#file="/home/gsd/data/zookeeper-root/version-2/log.100000001"
#ocurrence=3
#parts=2
#persist=2

#[[injection]]
#type="split_write"
#ocurrence=6
#file="/home/gsd/data/zk37-root/version-2/log.100000001"
#parts=3
#persist=[1,3]

[[injection]]
type="reorder"
op="write"
ocurrence=2
file="/home/gsd/clouds_stuff/tests/lfs_simple_tests/simple-root/output.txt"
persist=[3]
