[faults]
fifo_path="/tmp/faults.fifo"
[cache]
apply_eviction=false
[cache.simple]
custom_size="1gb"
blocks_per_page=1
# [cache.manual]
# io_block_size=4096
# page_size=4096
# no_pages=10
[filesystem]
log_all_operations=true
logfile="/home/gsd/lfs.log"

[[injection]]
type="split_write"
file="/home/gsd/data/zk37-root/version-2/log.100000001"
ocurrence=3
parts=10
persist=[1,4,8]