[faults]
fifo_path="/home/gsd/faults-example.fifo"
[cache]
apply_eviction=false
[cache.simple]
custom_size="1Mb"
blocks_per_page=1
# [cache.manual]
# io_block_size=4096
# page_size=4096
# no_pages=1
[filesystem]
sync_after_rename=true
log_all_operations=false