[faults]
fifo_path="/tmp/faults.fifo"
[cache]
apply_eviction=false
[cache.simple]
custom_size="1gb"
blocks_per_page=1
# [cache.manual]
# io_block_size=4096
# page_size=4096
# no_pages=10
[filesystem]
log_all_operations=true
logfile="/home/gsd/lazyfs_etcd.log"
#[[injection]]
#op="write"
#file="/home/gsd/data/zookeeper-root/version-2/log.100000001"
#persist=[3]
#[[injection]]
#op="write"
#file="/home/gsd/etcd-v3.4.25-linux-amd64/data-r/data.etcd/member/wal.tmp/0000000000000000-0000000000000000.wal"
#persist=[2]
#[[injection]]
#op="write"
#file="/home/gsd/etcd-v3.4.25-linux-amd64/data-r/data.etcd/member/snap/db"
#persist=[2]
[[injection]]
op="write"
file="/home/gsd/etcd-v2.3.0-linux-amd64/data-r/data.etcd/member/wal/0000000000000000-0000000000000000.wal"
persist=[2]
