name: build
on: push
jobs:
    build-lazyfs:
        runs-on: ubuntu-latest
        steps:
            - name: Check out repository code
              uses: actions/checkout@v2

            - name: Set up cache
              uses: actions/cache@v2
              with:
                  path: ~/build
                  key: build-lazyfs

            - name: Install dependencies
              run: sudo apt install g++ cmake libfuse3-dev libfuse3-3 fuse3

            - name: Set up FUSE configuration
              run: sudo sed -i "/\\s*user_allow_other/s/^#//g" "/etc/fuse.conf"

            - name: Build repo and run tests
              run: |
                sed -i 's/cmake \-DLAZYFS\_BUILD\_TESTS\=OFF \.\./cmake \-DLAZYFS\_\BUILD\_\TESTS\=ON \.\./g' lazyfs/build.sh 
                sudo sed -i "s|fifo_path=.*|fifo_path=\"$(pwd)\/faults-example.fifo\"|" lazyfs/config/default.toml
                sudo sed -s -i "s|\#define.*FAULTS_PIPE_PATH.*|\#define FAULTS_PIPE_PATH \"$(pwd)\/faults-example.fifo\"|" lazyfs/tests/*_clear_cache.cpp
                cd lazyfs/scripts && ./run-tests.sh -m /tmp/lazyfs -r /tmp/lazyfs-root/